#!/usr/bin/env python

neighborhood_list = {
            0: 'Bayview/Hunters Point',
            1: 'Bernal Heights',
            2: 'Castro',
            3: 'Chinatown',
            4: 'Civic Center/Tenderloin',
            5: 'Cole Valley',
            6: 'Crocker-Amazon',
            7: 'Diamond Heights',
            8: 'Dogpatch',
            9: 'Embarcadero',
            10: 'Excelsior',
            11: 'Financial District',
            12: 'Fisherman\'s Wharf',
            13: 'Glen Park',
            14: 'Haight-Ashbury',
            15: 'Hayes Valley',
            16: 'Ingleside',
            17: 'Inner Richmond',
            18: 'Inner Sunset',
            19: 'Japantown',
            20: 'Lakeside',
            21: 'Laurel Heights',
            22: 'Lower Haight',
            23: 'Lower Pac Heights',
            24: 'Marina/Cow Hollow',
            25: 'Miraloma',
            26: 'Mission',
            27: 'Mission Terrace',
            28: 'Nob Hill',
            29: 'Noe Valley',
            30: 'North Beach/Telegraph Hill',
            31: 'Outer Richmond',
            32: 'Outer Sunset',
            33: 'Pacific Heights',
            34: 'Parkside',
            35: 'Portola',
            36: 'Potrero Hill',
            37: 'Russian Hill',
            38: 'SOMA',
            39: 'Twin Peaks',
            40: 'Union Square',
            41: 'Visitacion Valley',
            42: 'West Portal',
            43: 'Western Addition/NOPA'
}

inv_neighborhood_list = dict((v,k) for k, v in neighborhood_list.iteritems())